/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthCallbackRouteImport } from './routes/auth-callback'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthSilentCallbackRouteImport } from './routes/auth/silent-callback'
import { Route as AuthLogoutCallbackRouteImport } from './routes/auth/logout-callback'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedProyectosIndexRouteImport } from './routes/_authenticated/proyectos/index'
import { Route as AuthenticatedOficinasIndexRouteImport } from './routes/_authenticated/oficinas/index'
import { Route as AuthenticatedFinanzasIndexRouteImport } from './routes/_authenticated/finanzas/index'
import { Route as AuthenticatedClientesIndexRouteImport } from './routes/_authenticated/clientes/index'
import { Route as AuthenticatedProyectosNuevoRouteImport } from './routes/_authenticated/proyectos/nuevo'
import { Route as AuthenticatedClientesNuevoRouteImport } from './routes/_authenticated/clientes/nuevo'
import { Route as AuthenticatedClientesClienteIdRouteImport } from './routes/_authenticated/clientes/$clienteId'
import { Route as AuthenticatedProyectosProyectoIdRouteRouteImport } from './routes/_authenticated/proyectos/$proyectoId/route'
import { Route as AuthenticatedProyectosProyectoIdIndexRouteImport } from './routes/_authenticated/proyectos/$proyectoId/index'
import { Route as AuthenticatedProyectosProyectoIdUbicacionRouteImport } from './routes/_authenticated/proyectos/$proyectoId/ubicacion'
import { Route as AuthenticatedProyectosProyectoIdResumenRouteImport } from './routes/_authenticated/proyectos/$proyectoId/resumen'
import { Route as AuthenticatedProyectosProyectoIdPresupuestoRouteImport } from './routes/_authenticated/proyectos/$proyectoId/presupuesto'
import { Route as AuthenticatedProyectosProyectoIdFotosRouteImport } from './routes/_authenticated/proyectos/$proyectoId/fotos'
import { Route as AuthenticatedProyectosProyectoIdFacturacionRouteImport } from './routes/_authenticated/proyectos/$proyectoId/facturacion'
import { Route as AuthenticatedProyectosProyectoIdDetallesRouteImport } from './routes/_authenticated/proyectos/$proyectoId/detalles'
import { Route as AuthenticatedProyectosProyectoIdAdminRouteImport } from './routes/_authenticated/proyectos/$proyectoId/admin'

const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth-callback',
  path: '/auth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthSilentCallbackRoute = AuthSilentCallbackRouteImport.update({
  id: '/auth/silent-callback',
  path: '/auth/silent-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutCallbackRoute = AuthLogoutCallbackRouteImport.update({
  id: '/auth/logout-callback',
  path: '/auth/logout-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProyectosIndexRoute =
  AuthenticatedProyectosIndexRouteImport.update({
    id: '/proyectos/',
    path: '/proyectos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOficinasIndexRoute =
  AuthenticatedOficinasIndexRouteImport.update({
    id: '/oficinas/',
    path: '/oficinas/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanzasIndexRoute =
  AuthenticatedFinanzasIndexRouteImport.update({
    id: '/finanzas/',
    path: '/finanzas/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientesIndexRoute =
  AuthenticatedClientesIndexRouteImport.update({
    id: '/clientes/',
    path: '/clientes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProyectosNuevoRoute =
  AuthenticatedProyectosNuevoRouteImport.update({
    id: '/proyectos/nuevo',
    path: '/proyectos/nuevo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientesNuevoRoute =
  AuthenticatedClientesNuevoRouteImport.update({
    id: '/clientes/nuevo',
    path: '/clientes/nuevo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientesClienteIdRoute =
  AuthenticatedClientesClienteIdRouteImport.update({
    id: '/clientes/$clienteId',
    path: '/clientes/$clienteId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProyectosProyectoIdRouteRoute =
  AuthenticatedProyectosProyectoIdRouteRouteImport.update({
    id: '/proyectos/$proyectoId',
    path: '/proyectos/$proyectoId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProyectosProyectoIdIndexRoute =
  AuthenticatedProyectosProyectoIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProyectosProyectoIdRouteRoute,
  } as any)
const AuthenticatedProyectosProyectoIdUbicacionRoute =
  AuthenticatedProyectosProyectoIdUbicacionRouteImport.update({
    id: '/ubicacion',
    path: '/ubicacion',
    getParentRoute: () => AuthenticatedProyectosProyectoIdRouteRoute,
  } as any)
const AuthenticatedProyectosProyectoIdResumenRoute =
  AuthenticatedProyectosProyectoIdResumenRouteImport.update({
    id: '/resumen',
    path: '/resumen',
    getParentRoute: () => AuthenticatedProyectosProyectoIdRouteRoute,
  } as any)
const AuthenticatedProyectosProyectoIdPresupuestoRoute =
  AuthenticatedProyectosProyectoIdPresupuestoRouteImport.update({
    id: '/presupuesto',
    path: '/presupuesto',
    getParentRoute: () => AuthenticatedProyectosProyectoIdRouteRoute,
  } as any)
const AuthenticatedProyectosProyectoIdFotosRoute =
  AuthenticatedProyectosProyectoIdFotosRouteImport.update({
    id: '/fotos',
    path: '/fotos',
    getParentRoute: () => AuthenticatedProyectosProyectoIdRouteRoute,
  } as any)
const AuthenticatedProyectosProyectoIdFacturacionRoute =
  AuthenticatedProyectosProyectoIdFacturacionRouteImport.update({
    id: '/facturacion',
    path: '/facturacion',
    getParentRoute: () => AuthenticatedProyectosProyectoIdRouteRoute,
  } as any)
const AuthenticatedProyectosProyectoIdDetallesRoute =
  AuthenticatedProyectosProyectoIdDetallesRouteImport.update({
    id: '/detalles',
    path: '/detalles',
    getParentRoute: () => AuthenticatedProyectosProyectoIdRouteRoute,
  } as any)
const AuthenticatedProyectosProyectoIdAdminRoute =
  AuthenticatedProyectosProyectoIdAdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => AuthenticatedProyectosProyectoIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/auth-callback': typeof AuthCallbackRoute
  '/auth/logout-callback': typeof AuthLogoutCallbackRoute
  '/auth/silent-callback': typeof AuthSilentCallbackRoute
  '/': typeof AuthenticatedIndexRoute
  '/proyectos/$proyectoId': typeof AuthenticatedProyectosProyectoIdRouteRouteWithChildren
  '/clientes/$clienteId': typeof AuthenticatedClientesClienteIdRoute
  '/clientes/nuevo': typeof AuthenticatedClientesNuevoRoute
  '/proyectos/nuevo': typeof AuthenticatedProyectosNuevoRoute
  '/clientes': typeof AuthenticatedClientesIndexRoute
  '/finanzas': typeof AuthenticatedFinanzasIndexRoute
  '/oficinas': typeof AuthenticatedOficinasIndexRoute
  '/proyectos': typeof AuthenticatedProyectosIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/proyectos/$proyectoId/admin': typeof AuthenticatedProyectosProyectoIdAdminRoute
  '/proyectos/$proyectoId/detalles': typeof AuthenticatedProyectosProyectoIdDetallesRoute
  '/proyectos/$proyectoId/facturacion': typeof AuthenticatedProyectosProyectoIdFacturacionRoute
  '/proyectos/$proyectoId/fotos': typeof AuthenticatedProyectosProyectoIdFotosRoute
  '/proyectos/$proyectoId/presupuesto': typeof AuthenticatedProyectosProyectoIdPresupuestoRoute
  '/proyectos/$proyectoId/resumen': typeof AuthenticatedProyectosProyectoIdResumenRoute
  '/proyectos/$proyectoId/ubicacion': typeof AuthenticatedProyectosProyectoIdUbicacionRoute
  '/proyectos/$proyectoId/': typeof AuthenticatedProyectosProyectoIdIndexRoute
}
export interface FileRoutesByTo {
  '/auth-callback': typeof AuthCallbackRoute
  '/auth/logout-callback': typeof AuthLogoutCallbackRoute
  '/auth/silent-callback': typeof AuthSilentCallbackRoute
  '/': typeof AuthenticatedIndexRoute
  '/clientes/$clienteId': typeof AuthenticatedClientesClienteIdRoute
  '/clientes/nuevo': typeof AuthenticatedClientesNuevoRoute
  '/proyectos/nuevo': typeof AuthenticatedProyectosNuevoRoute
  '/clientes': typeof AuthenticatedClientesIndexRoute
  '/finanzas': typeof AuthenticatedFinanzasIndexRoute
  '/oficinas': typeof AuthenticatedOficinasIndexRoute
  '/proyectos': typeof AuthenticatedProyectosIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/proyectos/$proyectoId/admin': typeof AuthenticatedProyectosProyectoIdAdminRoute
  '/proyectos/$proyectoId/detalles': typeof AuthenticatedProyectosProyectoIdDetallesRoute
  '/proyectos/$proyectoId/facturacion': typeof AuthenticatedProyectosProyectoIdFacturacionRoute
  '/proyectos/$proyectoId/fotos': typeof AuthenticatedProyectosProyectoIdFotosRoute
  '/proyectos/$proyectoId/presupuesto': typeof AuthenticatedProyectosProyectoIdPresupuestoRoute
  '/proyectos/$proyectoId/resumen': typeof AuthenticatedProyectosProyectoIdResumenRoute
  '/proyectos/$proyectoId/ubicacion': typeof AuthenticatedProyectosProyectoIdUbicacionRoute
  '/proyectos/$proyectoId': typeof AuthenticatedProyectosProyectoIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth-callback': typeof AuthCallbackRoute
  '/auth/logout-callback': typeof AuthLogoutCallbackRoute
  '/auth/silent-callback': typeof AuthSilentCallbackRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/proyectos/$proyectoId': typeof AuthenticatedProyectosProyectoIdRouteRouteWithChildren
  '/_authenticated/clientes/$clienteId': typeof AuthenticatedClientesClienteIdRoute
  '/_authenticated/clientes/nuevo': typeof AuthenticatedClientesNuevoRoute
  '/_authenticated/proyectos/nuevo': typeof AuthenticatedProyectosNuevoRoute
  '/_authenticated/clientes/': typeof AuthenticatedClientesIndexRoute
  '/_authenticated/finanzas/': typeof AuthenticatedFinanzasIndexRoute
  '/_authenticated/oficinas/': typeof AuthenticatedOficinasIndexRoute
  '/_authenticated/proyectos/': typeof AuthenticatedProyectosIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/proyectos/$proyectoId/admin': typeof AuthenticatedProyectosProyectoIdAdminRoute
  '/_authenticated/proyectos/$proyectoId/detalles': typeof AuthenticatedProyectosProyectoIdDetallesRoute
  '/_authenticated/proyectos/$proyectoId/facturacion': typeof AuthenticatedProyectosProyectoIdFacturacionRoute
  '/_authenticated/proyectos/$proyectoId/fotos': typeof AuthenticatedProyectosProyectoIdFotosRoute
  '/_authenticated/proyectos/$proyectoId/presupuesto': typeof AuthenticatedProyectosProyectoIdPresupuestoRoute
  '/_authenticated/proyectos/$proyectoId/resumen': typeof AuthenticatedProyectosProyectoIdResumenRoute
  '/_authenticated/proyectos/$proyectoId/ubicacion': typeof AuthenticatedProyectosProyectoIdUbicacionRoute
  '/_authenticated/proyectos/$proyectoId/': typeof AuthenticatedProyectosProyectoIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth-callback'
    | '/auth/logout-callback'
    | '/auth/silent-callback'
    | '/'
    | '/proyectos/$proyectoId'
    | '/clientes/$clienteId'
    | '/clientes/nuevo'
    | '/proyectos/nuevo'
    | '/clientes'
    | '/finanzas'
    | '/oficinas'
    | '/proyectos'
    | '/tasks'
    | '/proyectos/$proyectoId/admin'
    | '/proyectos/$proyectoId/detalles'
    | '/proyectos/$proyectoId/facturacion'
    | '/proyectos/$proyectoId/fotos'
    | '/proyectos/$proyectoId/presupuesto'
    | '/proyectos/$proyectoId/resumen'
    | '/proyectos/$proyectoId/ubicacion'
    | '/proyectos/$proyectoId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth-callback'
    | '/auth/logout-callback'
    | '/auth/silent-callback'
    | '/'
    | '/clientes/$clienteId'
    | '/clientes/nuevo'
    | '/proyectos/nuevo'
    | '/clientes'
    | '/finanzas'
    | '/oficinas'
    | '/proyectos'
    | '/tasks'
    | '/proyectos/$proyectoId/admin'
    | '/proyectos/$proyectoId/detalles'
    | '/proyectos/$proyectoId/facturacion'
    | '/proyectos/$proyectoId/fotos'
    | '/proyectos/$proyectoId/presupuesto'
    | '/proyectos/$proyectoId/resumen'
    | '/proyectos/$proyectoId/ubicacion'
    | '/proyectos/$proyectoId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth-callback'
    | '/auth/logout-callback'
    | '/auth/silent-callback'
    | '/_authenticated/'
    | '/_authenticated/proyectos/$proyectoId'
    | '/_authenticated/clientes/$clienteId'
    | '/_authenticated/clientes/nuevo'
    | '/_authenticated/proyectos/nuevo'
    | '/_authenticated/clientes/'
    | '/_authenticated/finanzas/'
    | '/_authenticated/oficinas/'
    | '/_authenticated/proyectos/'
    | '/_authenticated/tasks/'
    | '/_authenticated/proyectos/$proyectoId/admin'
    | '/_authenticated/proyectos/$proyectoId/detalles'
    | '/_authenticated/proyectos/$proyectoId/facturacion'
    | '/_authenticated/proyectos/$proyectoId/fotos'
    | '/_authenticated/proyectos/$proyectoId/presupuesto'
    | '/_authenticated/proyectos/$proyectoId/resumen'
    | '/_authenticated/proyectos/$proyectoId/ubicacion'
    | '/_authenticated/proyectos/$proyectoId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLogoutCallbackRoute: typeof AuthLogoutCallbackRoute
  AuthSilentCallbackRoute: typeof AuthSilentCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth-callback': {
      id: '/auth-callback'
      path: '/auth-callback'
      fullPath: '/auth-callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/silent-callback': {
      id: '/auth/silent-callback'
      path: '/auth/silent-callback'
      fullPath: '/auth/silent-callback'
      preLoaderRoute: typeof AuthSilentCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/logout-callback': {
      id: '/auth/logout-callback'
      path: '/auth/logout-callback'
      fullPath: '/auth/logout-callback'
      preLoaderRoute: typeof AuthLogoutCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/proyectos/': {
      id: '/_authenticated/proyectos/'
      path: '/proyectos'
      fullPath: '/proyectos'
      preLoaderRoute: typeof AuthenticatedProyectosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/oficinas/': {
      id: '/_authenticated/oficinas/'
      path: '/oficinas'
      fullPath: '/oficinas'
      preLoaderRoute: typeof AuthenticatedOficinasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finanzas/': {
      id: '/_authenticated/finanzas/'
      path: '/finanzas'
      fullPath: '/finanzas'
      preLoaderRoute: typeof AuthenticatedFinanzasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes/': {
      id: '/_authenticated/clientes/'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/proyectos/nuevo': {
      id: '/_authenticated/proyectos/nuevo'
      path: '/proyectos/nuevo'
      fullPath: '/proyectos/nuevo'
      preLoaderRoute: typeof AuthenticatedProyectosNuevoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes/nuevo': {
      id: '/_authenticated/clientes/nuevo'
      path: '/clientes/nuevo'
      fullPath: '/clientes/nuevo'
      preLoaderRoute: typeof AuthenticatedClientesNuevoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes/$clienteId': {
      id: '/_authenticated/clientes/$clienteId'
      path: '/clientes/$clienteId'
      fullPath: '/clientes/$clienteId'
      preLoaderRoute: typeof AuthenticatedClientesClienteIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/proyectos/$proyectoId': {
      id: '/_authenticated/proyectos/$proyectoId'
      path: '/proyectos/$proyectoId'
      fullPath: '/proyectos/$proyectoId'
      preLoaderRoute: typeof AuthenticatedProyectosProyectoIdRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/proyectos/$proyectoId/': {
      id: '/_authenticated/proyectos/$proyectoId/'
      path: '/'
      fullPath: '/proyectos/$proyectoId/'
      preLoaderRoute: typeof AuthenticatedProyectosProyectoIdIndexRouteImport
      parentRoute: typeof AuthenticatedProyectosProyectoIdRouteRoute
    }
    '/_authenticated/proyectos/$proyectoId/ubicacion': {
      id: '/_authenticated/proyectos/$proyectoId/ubicacion'
      path: '/ubicacion'
      fullPath: '/proyectos/$proyectoId/ubicacion'
      preLoaderRoute: typeof AuthenticatedProyectosProyectoIdUbicacionRouteImport
      parentRoute: typeof AuthenticatedProyectosProyectoIdRouteRoute
    }
    '/_authenticated/proyectos/$proyectoId/resumen': {
      id: '/_authenticated/proyectos/$proyectoId/resumen'
      path: '/resumen'
      fullPath: '/proyectos/$proyectoId/resumen'
      preLoaderRoute: typeof AuthenticatedProyectosProyectoIdResumenRouteImport
      parentRoute: typeof AuthenticatedProyectosProyectoIdRouteRoute
    }
    '/_authenticated/proyectos/$proyectoId/presupuesto': {
      id: '/_authenticated/proyectos/$proyectoId/presupuesto'
      path: '/presupuesto'
      fullPath: '/proyectos/$proyectoId/presupuesto'
      preLoaderRoute: typeof AuthenticatedProyectosProyectoIdPresupuestoRouteImport
      parentRoute: typeof AuthenticatedProyectosProyectoIdRouteRoute
    }
    '/_authenticated/proyectos/$proyectoId/fotos': {
      id: '/_authenticated/proyectos/$proyectoId/fotos'
      path: '/fotos'
      fullPath: '/proyectos/$proyectoId/fotos'
      preLoaderRoute: typeof AuthenticatedProyectosProyectoIdFotosRouteImport
      parentRoute: typeof AuthenticatedProyectosProyectoIdRouteRoute
    }
    '/_authenticated/proyectos/$proyectoId/facturacion': {
      id: '/_authenticated/proyectos/$proyectoId/facturacion'
      path: '/facturacion'
      fullPath: '/proyectos/$proyectoId/facturacion'
      preLoaderRoute: typeof AuthenticatedProyectosProyectoIdFacturacionRouteImport
      parentRoute: typeof AuthenticatedProyectosProyectoIdRouteRoute
    }
    '/_authenticated/proyectos/$proyectoId/detalles': {
      id: '/_authenticated/proyectos/$proyectoId/detalles'
      path: '/detalles'
      fullPath: '/proyectos/$proyectoId/detalles'
      preLoaderRoute: typeof AuthenticatedProyectosProyectoIdDetallesRouteImport
      parentRoute: typeof AuthenticatedProyectosProyectoIdRouteRoute
    }
    '/_authenticated/proyectos/$proyectoId/admin': {
      id: '/_authenticated/proyectos/$proyectoId/admin'
      path: '/admin'
      fullPath: '/proyectos/$proyectoId/admin'
      preLoaderRoute: typeof AuthenticatedProyectosProyectoIdAdminRouteImport
      parentRoute: typeof AuthenticatedProyectosProyectoIdRouteRoute
    }
  }
}

interface AuthenticatedProyectosProyectoIdRouteRouteChildren {
  AuthenticatedProyectosProyectoIdAdminRoute: typeof AuthenticatedProyectosProyectoIdAdminRoute
  AuthenticatedProyectosProyectoIdDetallesRoute: typeof AuthenticatedProyectosProyectoIdDetallesRoute
  AuthenticatedProyectosProyectoIdFacturacionRoute: typeof AuthenticatedProyectosProyectoIdFacturacionRoute
  AuthenticatedProyectosProyectoIdFotosRoute: typeof AuthenticatedProyectosProyectoIdFotosRoute
  AuthenticatedProyectosProyectoIdPresupuestoRoute: typeof AuthenticatedProyectosProyectoIdPresupuestoRoute
  AuthenticatedProyectosProyectoIdResumenRoute: typeof AuthenticatedProyectosProyectoIdResumenRoute
  AuthenticatedProyectosProyectoIdUbicacionRoute: typeof AuthenticatedProyectosProyectoIdUbicacionRoute
  AuthenticatedProyectosProyectoIdIndexRoute: typeof AuthenticatedProyectosProyectoIdIndexRoute
}

const AuthenticatedProyectosProyectoIdRouteRouteChildren: AuthenticatedProyectosProyectoIdRouteRouteChildren =
  {
    AuthenticatedProyectosProyectoIdAdminRoute:
      AuthenticatedProyectosProyectoIdAdminRoute,
    AuthenticatedProyectosProyectoIdDetallesRoute:
      AuthenticatedProyectosProyectoIdDetallesRoute,
    AuthenticatedProyectosProyectoIdFacturacionRoute:
      AuthenticatedProyectosProyectoIdFacturacionRoute,
    AuthenticatedProyectosProyectoIdFotosRoute:
      AuthenticatedProyectosProyectoIdFotosRoute,
    AuthenticatedProyectosProyectoIdPresupuestoRoute:
      AuthenticatedProyectosProyectoIdPresupuestoRoute,
    AuthenticatedProyectosProyectoIdResumenRoute:
      AuthenticatedProyectosProyectoIdResumenRoute,
    AuthenticatedProyectosProyectoIdUbicacionRoute:
      AuthenticatedProyectosProyectoIdUbicacionRoute,
    AuthenticatedProyectosProyectoIdIndexRoute:
      AuthenticatedProyectosProyectoIdIndexRoute,
  }

const AuthenticatedProyectosProyectoIdRouteRouteWithChildren =
  AuthenticatedProyectosProyectoIdRouteRoute._addFileChildren(
    AuthenticatedProyectosProyectoIdRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedProyectosProyectoIdRouteRoute: typeof AuthenticatedProyectosProyectoIdRouteRouteWithChildren
  AuthenticatedClientesClienteIdRoute: typeof AuthenticatedClientesClienteIdRoute
  AuthenticatedClientesNuevoRoute: typeof AuthenticatedClientesNuevoRoute
  AuthenticatedProyectosNuevoRoute: typeof AuthenticatedProyectosNuevoRoute
  AuthenticatedClientesIndexRoute: typeof AuthenticatedClientesIndexRoute
  AuthenticatedFinanzasIndexRoute: typeof AuthenticatedFinanzasIndexRoute
  AuthenticatedOficinasIndexRoute: typeof AuthenticatedOficinasIndexRoute
  AuthenticatedProyectosIndexRoute: typeof AuthenticatedProyectosIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedProyectosProyectoIdRouteRoute:
    AuthenticatedProyectosProyectoIdRouteRouteWithChildren,
  AuthenticatedClientesClienteIdRoute: AuthenticatedClientesClienteIdRoute,
  AuthenticatedClientesNuevoRoute: AuthenticatedClientesNuevoRoute,
  AuthenticatedProyectosNuevoRoute: AuthenticatedProyectosNuevoRoute,
  AuthenticatedClientesIndexRoute: AuthenticatedClientesIndexRoute,
  AuthenticatedFinanzasIndexRoute: AuthenticatedFinanzasIndexRoute,
  AuthenticatedOficinasIndexRoute: AuthenticatedOficinasIndexRoute,
  AuthenticatedProyectosIndexRoute: AuthenticatedProyectosIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLogoutCallbackRoute: AuthLogoutCallbackRoute,
  AuthSilentCallbackRoute: AuthSilentCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
