/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthSilentCallbackRouteImport } from './routes/auth/silent-callback'
import { Route as AuthLogoutCallbackRouteImport } from './routes/auth/logout-callback'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedProyectosIndexRouteImport } from './routes/_authenticated/proyectos/index'
import { Route as AuthenticatedClientesIndexRouteImport } from './routes/_authenticated/clientes/index'
import { Route as AuthenticatedProyectosNuevoRouteImport } from './routes/_authenticated/proyectos/nuevo'
import { Route as AuthenticatedProyectosProyectoIdRouteImport } from './routes/_authenticated/proyectos/$proyectoId'
import { Route as AuthenticatedClientesNuevoRouteImport } from './routes/_authenticated/clientes/nuevo'
import { Route as AuthenticatedClientesClienteIdRouteImport } from './routes/_authenticated/clientes/$clienteId'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthSilentCallbackRoute = AuthSilentCallbackRouteImport.update({
  id: '/auth/silent-callback',
  path: '/auth/silent-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutCallbackRoute = AuthLogoutCallbackRouteImport.update({
  id: '/auth/logout-callback',
  path: '/auth/logout-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProyectosIndexRoute =
  AuthenticatedProyectosIndexRouteImport.update({
    id: '/proyectos/',
    path: '/proyectos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientesIndexRoute =
  AuthenticatedClientesIndexRouteImport.update({
    id: '/clientes/',
    path: '/clientes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProyectosNuevoRoute =
  AuthenticatedProyectosNuevoRouteImport.update({
    id: '/proyectos/nuevo',
    path: '/proyectos/nuevo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProyectosProyectoIdRoute =
  AuthenticatedProyectosProyectoIdRouteImport.update({
    id: '/proyectos/$proyectoId',
    path: '/proyectos/$proyectoId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientesNuevoRoute =
  AuthenticatedClientesNuevoRouteImport.update({
    id: '/clientes/nuevo',
    path: '/clientes/nuevo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientesClienteIdRoute =
  AuthenticatedClientesClienteIdRouteImport.update({
    id: '/clientes/$clienteId',
    path: '/clientes/$clienteId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/logout-callback': typeof AuthLogoutCallbackRoute
  '/auth/silent-callback': typeof AuthSilentCallbackRoute
  '/': typeof AuthenticatedIndexRoute
  '/clientes/$clienteId': typeof AuthenticatedClientesClienteIdRoute
  '/clientes/nuevo': typeof AuthenticatedClientesNuevoRoute
  '/proyectos/$proyectoId': typeof AuthenticatedProyectosProyectoIdRoute
  '/proyectos/nuevo': typeof AuthenticatedProyectosNuevoRoute
  '/clientes': typeof AuthenticatedClientesIndexRoute
  '/proyectos': typeof AuthenticatedProyectosIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
}
export interface FileRoutesByTo {
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/logout-callback': typeof AuthLogoutCallbackRoute
  '/auth/silent-callback': typeof AuthSilentCallbackRoute
  '/': typeof AuthenticatedIndexRoute
  '/clientes/$clienteId': typeof AuthenticatedClientesClienteIdRoute
  '/clientes/nuevo': typeof AuthenticatedClientesNuevoRoute
  '/proyectos/$proyectoId': typeof AuthenticatedProyectosProyectoIdRoute
  '/proyectos/nuevo': typeof AuthenticatedProyectosNuevoRoute
  '/clientes': typeof AuthenticatedClientesIndexRoute
  '/proyectos': typeof AuthenticatedProyectosIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/logout-callback': typeof AuthLogoutCallbackRoute
  '/auth/silent-callback': typeof AuthSilentCallbackRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/clientes/$clienteId': typeof AuthenticatedClientesClienteIdRoute
  '/_authenticated/clientes/nuevo': typeof AuthenticatedClientesNuevoRoute
  '/_authenticated/proyectos/$proyectoId': typeof AuthenticatedProyectosProyectoIdRoute
  '/_authenticated/proyectos/nuevo': typeof AuthenticatedProyectosNuevoRoute
  '/_authenticated/clientes/': typeof AuthenticatedClientesIndexRoute
  '/_authenticated/proyectos/': typeof AuthenticatedProyectosIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth/callback'
    | '/auth/logout-callback'
    | '/auth/silent-callback'
    | '/'
    | '/clientes/$clienteId'
    | '/clientes/nuevo'
    | '/proyectos/$proyectoId'
    | '/proyectos/nuevo'
    | '/clientes'
    | '/proyectos'
    | '/tasks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth/callback'
    | '/auth/logout-callback'
    | '/auth/silent-callback'
    | '/'
    | '/clientes/$clienteId'
    | '/clientes/nuevo'
    | '/proyectos/$proyectoId'
    | '/proyectos/nuevo'
    | '/clientes'
    | '/proyectos'
    | '/tasks'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth/callback'
    | '/auth/logout-callback'
    | '/auth/silent-callback'
    | '/_authenticated/'
    | '/_authenticated/clientes/$clienteId'
    | '/_authenticated/clientes/nuevo'
    | '/_authenticated/proyectos/$proyectoId'
    | '/_authenticated/proyectos/nuevo'
    | '/_authenticated/clientes/'
    | '/_authenticated/proyectos/'
    | '/_authenticated/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLogoutCallbackRoute: typeof AuthLogoutCallbackRoute
  AuthSilentCallbackRoute: typeof AuthSilentCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/silent-callback': {
      id: '/auth/silent-callback'
      path: '/auth/silent-callback'
      fullPath: '/auth/silent-callback'
      preLoaderRoute: typeof AuthSilentCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/logout-callback': {
      id: '/auth/logout-callback'
      path: '/auth/logout-callback'
      fullPath: '/auth/logout-callback'
      preLoaderRoute: typeof AuthLogoutCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/proyectos/': {
      id: '/_authenticated/proyectos/'
      path: '/proyectos'
      fullPath: '/proyectos'
      preLoaderRoute: typeof AuthenticatedProyectosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes/': {
      id: '/_authenticated/clientes/'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/proyectos/nuevo': {
      id: '/_authenticated/proyectos/nuevo'
      path: '/proyectos/nuevo'
      fullPath: '/proyectos/nuevo'
      preLoaderRoute: typeof AuthenticatedProyectosNuevoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/proyectos/$proyectoId': {
      id: '/_authenticated/proyectos/$proyectoId'
      path: '/proyectos/$proyectoId'
      fullPath: '/proyectos/$proyectoId'
      preLoaderRoute: typeof AuthenticatedProyectosProyectoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes/nuevo': {
      id: '/_authenticated/clientes/nuevo'
      path: '/clientes/nuevo'
      fullPath: '/clientes/nuevo'
      preLoaderRoute: typeof AuthenticatedClientesNuevoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes/$clienteId': {
      id: '/_authenticated/clientes/$clienteId'
      path: '/clientes/$clienteId'
      fullPath: '/clientes/$clienteId'
      preLoaderRoute: typeof AuthenticatedClientesClienteIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedClientesClienteIdRoute: typeof AuthenticatedClientesClienteIdRoute
  AuthenticatedClientesNuevoRoute: typeof AuthenticatedClientesNuevoRoute
  AuthenticatedProyectosProyectoIdRoute: typeof AuthenticatedProyectosProyectoIdRoute
  AuthenticatedProyectosNuevoRoute: typeof AuthenticatedProyectosNuevoRoute
  AuthenticatedClientesIndexRoute: typeof AuthenticatedClientesIndexRoute
  AuthenticatedProyectosIndexRoute: typeof AuthenticatedProyectosIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedClientesClienteIdRoute: AuthenticatedClientesClienteIdRoute,
  AuthenticatedClientesNuevoRoute: AuthenticatedClientesNuevoRoute,
  AuthenticatedProyectosProyectoIdRoute: AuthenticatedProyectosProyectoIdRoute,
  AuthenticatedProyectosNuevoRoute: AuthenticatedProyectosNuevoRoute,
  AuthenticatedClientesIndexRoute: AuthenticatedClientesIndexRoute,
  AuthenticatedProyectosIndexRoute: AuthenticatedProyectosIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLogoutCallbackRoute: AuthLogoutCallbackRoute,
  AuthSilentCallbackRoute: AuthSilentCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
